In [2]:
import numpy as np

In [3]:
import random

In [4]:
import csv
import pandas

In [5]:
address_data = pandas.read_csv('../data/commadongho.csv', sep = ',', header = None)
address_data_ = address_data
address = np.array([x.split(';') for x in address_data_[0]])

In [6]:
address_data_

,0,1,2,3,4,5
0,d.recipientaddr,d.recipientaddrrefined,d.addr1,d.addr2,d.buildingdong,d.buildingho
1,경기도 광주시 오포읍 양벌리 1104 양벌리 세양 청마루 아파트 104-502,"경기 광주시 오포읍 양촌안길 35-17 104동 502호 (양벌리 1104번지, 양...",경기 광주시 오포읍 양촌안길 35-17,"104동 502호 (양벌리 1104번지, 양벌리세양청마루아파트)",NaN,NaN
2,대전광역시 서구 도산로403번길 21 355호 ( 탄방동 ),"대전 서구 도산로403번길 21 355호 (탄방동 80-1번지, 전자타운)",대전 서구 도산로403번길 21,"355호 (탄방동 80-1번지, 전자타운)",NaN,NaN
3,인천광역시 부평구 평천로 447 삼산구주공1단지102동801호,"인천 부평구 평천로 447 102동 801호 (삼산1동 157번지, 삼산구주공1단지)",인천 부평구 평천로 447,"102동 801호 (삼산1동 157번지, 삼산구주공1단지)",NaN,NaN
4,서울특별시 관악구 신림동 1423-23 801호,서울 관악구 남부순환로181길 25-10 801호 (신림동 1423-23번지),서울 관악구 남부순환로181길 25-10,801호 (신림동 1423-23번지),NaN,NaN
5,경기도 고양시 일산동구 식사동 1498 위시티일산자이2단지아파트 상가 2층 207호...,경기 고양시 일산동구 위시티4로 46 상가 2층 207호 수피아에스테틱 (식사동 1...,경기 고양시 일산동구 위시티4로 46,"상가 2층 207호 수피아에스테틱 (식사동 1498번지, 위시티일산자이2단지아파트)",NaN,NaN
6,"경기도 의왕시 오전천로 54 103동 1403호 ( 오전동, 민들레베스파트 )","경기 의왕시 오전천로 54 103동 1403호 (오전동 388-1번지, 민들레베스파트)",경기 의왕시 오전천로 54,"103동 1403호 (오전동 388-1번지, 민들레베스파트)",NaN,NaN
7,서울특별시 관악구 남부순환로272길 24 102호 ( 남현동 ),서울 관악구 남부순환로272길 24 102호 (남현동 1065-13번지),서울 관악구 남부순환로272길 24,102호 (남현동 1065-13번지),NaN,NaN
8,부산광역시 해운대구 재송동 1041-3 금호아파트 101동 405호,"부산 해운대구 재반로 141 101동 405호 (재송2동 1043-1번지, 금호아파트)",부산 해운대구 재반로 141,"101동 405호 (재송2동 1043-1번지, 금호아파트)",NaN,NaN
9,"경상북도 구미시 해마루공원로 111 옥계우미린 103동 601호 ( 옥계동, 구미옥...","경북 구미시 해마루공원로 111 103동 601호 (옥계동 906번지, 옥계우미린)",경북 구미시 해마루공원로 111,"103동 601호 (옥계동 906번지, 옥계우미린)",NaN,NaN
10,부산광역시 강서구 신호동 296-1 부산신호사랑으로부영1차 112동903호,"부산 강서구 신호산단3로 27 112동 903호 (신호동 296-1번지, 부산신호사...",부산 강서구 신호산단3로 27,"112동 903호 (신호동 296-1번지, 부산신호사랑으로부영1차)",NaN,NaN
11,충청남도 천안시 서북구 두정동 1377 프라지움9차 420호,"충남 천안시 서북구 오성로 115 420호 (두정동 1377번지, 프라지움9차)",충남 천안시 서북구 오성로 115,"420호 (두정동 1377번지, 프라지움9차)",NaN,NaN
12,경기도 고양시 덕양구 원흥동 669 삼송마을14단지아파트 1403동 206호,"경기 고양시 덕양구 권율대로 726 1403동 206호 (원흥동 669번지, 삼송마...",경기 고양시 덕양구 권율대로 726,"1403동 206호 (원흥동 669번지, 삼송마을14단지아파트)",NaN,NaN
13,서울특별시 강남구 대치4동 롯데캐슬아파트 102-503,"서울 강남구 삼성로85길 11 102동 503호 (대치4동 893번지, 롯데캐슬아파트)",서울 강남구 삼성로85길 11,"102동 503호 (대치4동 893번지, 롯데캐슬아파트)",NaN,NaN
14,"서울특별시 용산구 녹사평대로 66 푸르지오아파트 208동102호 ( 동빙고동, 용산...","서울 용산구 녹사평대로 66 208동 102호 (동빙고동 316번지, 푸르지오아파트)",서울 용산구 녹사평대로 66,"208동 102호 (동빙고동 316번지, 푸르지오아파트)",NaN,NaN
15,전라남도 신안군 안좌면 여흘길 41-126 -,전남 신안군 안좌면 여흘길 41-126 (여흘리 624번지),전남 신안군 안좌면 여흘길 41-126,(여흘리 624번지),NaN,NaN
16,제주특별자치도 제주시 이도일동 1258-1 장원스카이펠리스 장원스카이팰리스 1206호,"제주 제주시 동광로3길 3 1206호 (이도일동 1258-1번지, 장원스카이펠리스장...",제주 제주시 동광로3길 3,"1206호 (이도일동 1258-1번지, 장원스카이펠리스장원스카이팰리스)",NaN,NaN
17,전라남도 장흥군 회진면 회진리 2141-4 2층,전남 장흥군 회진면 회진선창길 22-1 2층 (회진리 2141-4번지),전남 장흥군 회진면 회진선창길 22-1,2층 (회진리 2141-4번지),NaN,NaN
18,대구광역시 달성군 현풍면 중리 학산아파트 205동 101호,"대구 달성군 현풍면 현풍동로 23 205동 101호 (중리 335번지, 학산아파트)",대구 달성군 현풍면 현풍동로 23,"205동 101호 (중리 335번지, 학산아파트)",NaN,NaN
19,경기도 성남시 분당구 야탑동 시그마3 1140호,"경기 성남시 분당구 장미로 78 1140호 (야탑동 360-1번지, 시그마3)",경기 성남시 분당구 장미로 78,"1140호 (야탑동 360-1번지, 시그마3)",NaN,NaN
20,울산광역시 울주군 온양읍 대안리 543-11 대안현대아파트 106동 1303호,"울산 울주군 온양읍 남창강변로 102 106동 1303호 (대안리 543-11번지,...",울산 울주군 온양읍 남창강변로 102,"106동 1303호 (대안리 543-11번지, 대안현대아파트)",NaN,NaN
21,대구광역시 수성구 만촌동 1050-134 감람나무 201호,"대구 수성구 청호로96안길 34 201호 (만촌3동 1050-134번지, 감람나무)",대구 수성구 청호로96안길 34,"201호 (만촌3동 1050-134번지, 감람나무)",NaN,NaN
22,인천광역시 계양구 용종동 209-4 계양프라자6층 태성당구장,"인천 계양구 오조산공원로 22 6층 태성당구장 (용종동 209-4번지, 계양프라자)",인천 계양구 오조산공원로 22,"6층 태성당구장 (용종동 209-4번지, 계양프라자)",NaN,NaN
23,"경상북도 김천시 용전1로 9 108동 1605호 엠코타운 ( 율곡동,엠코타운 더 플...","경북 김천시 용전1로 9 108동 1605호 (율곡동 773번지, 엠코타운)",경북 김천시 용전1로 9,"108동 1605호 (율곡동 773번지, 엠코타운)",NaN,NaN
24,경기도 화성시 남양읍 시청로102번길 51 시티프라디움1차 111동703호 ( 시티...,경기 화성시 남양읍 시청로102번길 51 111동 703호 (남양리 1815-12번...,경기 화성시 남양읍 시청로102번길 51,"111동 703호 (남양리 1815-12번지, 시티프라디움1차)",NaN,NaN
25,경기도 안성시 당왕동 535 대우경남아파트 202동 1504호,"경기 안성시 고수2로 20 202동 1504호 (당왕동 535번지, 대우경남아파트)",경기 안성시 고수2로 20,"202동 1504호 (당왕동 535번지, 대우경남아파트)",NaN,NaN
26,충청북도 청주시 청원구 율량동 1061번지 태산기획,충북 청주시 청원구 충청대로115번길 15-7 태산기획 (율량동 1061번지),충북 청주시 청원구 충청대로115번길 15-7,태산기획 (율량동 1061번지),NaN,NaN
27,경상남도 창원시 성산구 대방동 덕산2차아파트 (201~207동) 203동1006호,"경남 창원시 성산구 대암로 272 203동 1006호 (대방동 375번지, 덕산2차...",경남 창원시 성산구 대암로 272,"203동 1006호 (대방동 375번지, 덕산2차아파트)",NaN,NaN
28,서울특별시 은평구 대조동 92-11 리안쉐르빌 401호,"서울 은평구 역말로 161-15 401호 (대조동 92-11번지, 리안쉐르빌)",서울 은평구 역말로 161-15,"401호 (대조동 92-11번지, 리안쉐르빌)",NaN,NaN
29,전라북도 전주시 완산구 효자동2가 1117-68 장미연립 장미연립101호,"전북 전주시 완산구 거마평로 229 101호 (효자동2가 1117-68번지, 장미연...",전북 전주시 완산구 거마평로 229,"101호 (효자동2가 1117-68번지, 장미연립장미연립)",NaN,NaN
...,...,...,...,...,...,...
971,부산광역시 사하구 괴정로43번길 23 시골돼지국밥 ( 하단동 ),부산 사하구 괴정로43번길 23 시골돼지국밥 (하단1동 155-4번지),부산 사하구 괴정로43번길 23,시골돼지국밥 (하단1동 155-4번지),NaN,NaN
972,대구광역시 남구 명덕로64길 26 송원빌 302호,"대구 남구 명덕로64길 26 302호 (이천동 197-5번지, 송원빌)",대구 남구 명덕로64길 26,"302호 (이천동 197-5번지, 송원빌)",NaN,NaN
973,경상북도 칠곡군 석적읍 남율리 1087 칠곡남율효성해링턴플레이스1단지 104동1803호,"경북 칠곡군 석적읍 남율로9길 33 104동 1803호 (남율리 1087번지, 칠곡...",경북 칠곡군 석적읍 남율로9길 33,"104동 1803호 (남율리 1087번지, 칠곡남율효성해링턴플레이스1단지)",NaN,NaN
974,인천광역시 서구 당하동 1107-9 노송마을 305호,"인천 서구 청마로134번길 13-3 305호 (당하동 1107-9번지, 노송마을)",인천 서구 청마로134번길 13-3,"305호 (당하동 1107-9번지, 노송마을)",NaN,NaN
975,경기도 파주시 야당동 1031 휴먼시아 한빛마을 806동602호,"경기 파주시 와석순환로 15 806동 602호 (야당동 1031번지, 휴먼시아한빛마을)",경기 파주시 와석순환로 15,"806동 602호 (야당동 1031번지, 휴먼시아한빛마을)",NaN,NaN
976,광주광역시 광산구 신가동 대방노블랜드아파트 (101~112동) 103-603,"광주 광산구 수등로76번길 40 103동 603호 (신가동 1304번지, 대방노블랜...",광주 광산구 수등로76번길 40,"103동 603호 (신가동 1304번지, 대방노블랜드아파트)",NaN,NaN
977,부산 부산진구 양정2동 270-3번지 엘리시아@903호,"부산 부산진구 중앙대로 966 903호 (양정2동 270-3번지, 엘리시아아파트)",부산 부산진구 중앙대로 966,"903호 (양정2동 270-3번지, 엘리시아아파트)",NaN,NaN
978,"대구광역시 동구 화랑로25길 17 용림아파트606호 ( 효목동, 용림아파트 )","대구 동구 화랑로25길 17 606호 (효목2동 551번지, 용림아파트)",대구 동구 화랑로25길 17,"606호 (효목2동 551번지, 용림아파트)",NaN,NaN
979,대구광역시 동구 율하동 1093 우방아이유쉘아파트 108동304호,"대구 동구 금호강변로3길 22 108동 304호 (율하동 1093번지, 우방아이유쉘...",대구 동구 금호강변로3길 22,"108동 304호 (율하동 1093번지, 우방아이유쉘아파트)",NaN,NaN
980,대구광역시 달성군 다사읍 세천로 187 세천한라비발디 103동 1104호 ( 대구세...,"대구 달성군 다사읍 세천로 187 103동 1104호 (세천리 1566-1번지, 세...",대구 달성군 다사읍 세천로 187,"103동 1104호 (세천리 1566-1번지, 세천한라비발디)",NaN,NaN
981,인천광역시 남구 용현동 647 용현2단지금호타운 201-1004,"인천 남구 매소홀로 68 201동 1004호 (용현5동 647번지, 용현2단지금호타운)",인천 남구 매소홀로 68,"201동 1004호 (용현5동 647번지, 용현2단지금호타운)",NaN,NaN
982,울산광역시 남구 삼산동 183-1 삼산리버뷰웰가주상복합 101동1405호,"울산 남구 정동로 142 101동 1405호 (삼산동 183-1번지, 삼산리버뷰웰가...",울산 남구 정동로 142,"101동 1405호 (삼산동 183-1번지, 삼산리버뷰웰가주상복합)",NaN,NaN
983,세종특별자치시 도담동 651 도램마을 12단지 모아엘가에듀힐 1204동 1102호,"세종 보듬4로 19 1204동 1102호 (도담동 651번지, 모아엘가에듀힐)",세종 보듬4로 19,"1204동 1102호 (도담동 651번지, 모아엘가에듀힐)",NaN,NaN
984,경기도 고양시 일산동구 장항동 896-1 동양생명빌딩2층 KB손해보험 일산TC지점,경기 고양시 일산동구 중앙로 1165 2층 KB손해보험 일산TC지점 (장항2동 89...,경기 고양시 일산동구 중앙로 1165,"2층 KB손해보험 일산TC지점 (장항2동 896-1번지, 동양생명빌딩)",NaN,NaN
985,서울특별시 서대문구 북아현로18길 58 지계 ( 북아현동 ),서울 서대문구 북아현로18길 58 지계 (북아현동 1-147번지),서울 서대문구 북아현로18길 58,지계 (북아현동 1-147번지),NaN,NaN
986,부산광역시 기장군 정관면 용수리 협성르네상스 (101~107동) 104동205호,"부산 기장군 정관읍 정관4로 68 104동 205호 (용수리 1318번지, 협성르네상스)",부산 기장군 정관읍 정관4로 68,"104동 205호 (용수리 1318번지, 협성르네상스)",NaN,NaN
987,서울특별시 양천구 신정동 목동신시가지9단지@931동1101호,"서울 양천구 목동서로 340 931동 1101호 (신정1동 312번지, 목동신시가지...",서울 양천구 목동서로 340,"931동 1101호 (신정1동 312번지, 목동신시가지9단지아파트)",NaN,NaN
988,서울특별시 강남구 청담동 9-12 비노에삐아또,서울 강남구 학동로77길 50 비노에삐아또 (청담동 9-12번지),서울 강남구 학동로77길 50,비노에삐아또 (청담동 9-12번지),NaN,NaN
989,경기도 화성시 능동 동탄숲속마을자연앤경남아너스빌아파트 (801~809동) 801동 ...,"경기 화성시 동탄숲속로 103 801동 1403호 (능동 1115번지, 동탄숲속마을...",경기 화성시 동탄숲속로 103,"801동 1403호 (능동 1115번지, 동탄숲속마을자연앤경남아너스빌아파트)",NaN,NaN
990,"경기도 안산시 상록구 초당5길 6 B동 302호 ( 사동,예진아트빌 )","경기 안산시 상록구 초당5길 6 B동 302호 (사동 1391-2번지, 예진아트빌)",경기 안산시 상록구 초당5길 6,"B동 302호 (사동 1391-2번지, 예진아트빌)",NaN,NaN
991,대전광역시 중구 대종로 512 3층 J당구하우스 ( 은행동 ),"대전 중구 대종로 512 3층 (은행동 126-9번지, J당구하우스)",대전 중구 대종로 512,"3층 (은행동 126-9번지, J당구하우스)",NaN,NaN
992,"인천광역시 부평구 부평북로 463 312동 1403호 ( 삼산동,주공미래타운3단지 )","인천 부평구 부평북로 463 312동 1403호 (삼산1동 390-6번지, 주공미래...",인천 부평구 부평북로 463,"312동 1403호 (삼산1동 390-6번지, 주공미래타운3단지)",NaN,NaN
993,경상북도 경산시 진량읍 초원길 53-4 초원장미 아파트 101동305호,"경북 경산시 진량읍 초원길 53-4 101동 305호 (양기리 403-3번지, 초원...",경북 경산시 진량읍 초원길 53-4,"101동 305호 (양기리 403-3번지, 초원장미아파트)",NaN,NaN
994,서울특별시 관악구 낙성대역6길 8-4 303호,"서울 관악구 낙성대역6길 8-4 303호 (인헌동 196-269번지, 벧엘하우스)",서울 관악구 낙성대역6길 8-4,"303호 (인헌동 196-269번지, 벧엘하우스)",NaN,NaN
995,"경기도 안산시 단원구 광덕2로 241 802동 203호 ( 고잔동, 그린빌주공8단지...","경기 안산시 단원구 광덕2로 241 802동 203호 (고잔동 766번지, 그린빌주...",경기 안산시 단원구 광덕2로 241,"802동 203호 (고잔동 766번지, 그린빌주공8단지아파트)",NaN,NaN
996,울산광역시 동구 방어동 207-3 허브팰리츠 205-1102,"울산 동구 서진길 59 205동 1102호 (방어동 207-3번지, 허브팰리츠)",울산 동구 서진길 59,"205동 1102호 (방어동 207-3번지, 허브팰리츠)",NaN,NaN
997,경기도 의정부시 신곡동 597-99 삼노맨션 삼노맨션c동 101호,"경기 의정부시 시민로200번길 9 C동 101호 (신곡1동 597-99번지, 삼노맨...",경기 의정부시 시민로200번길 9,"C동 101호 (신곡1동 597-99번지, 삼노맨션삼노맨션)",NaN,NaN
998,경기도 부천시 약대동 209 부천위브트레지움2단지아파트 211동 1101호,"경기 부천시 도약로 206 211동 1101호 (약대동 209번지, 부천위브트레지움...",경기 부천시 도약로 206,"211동 1101호 (약대동 209번지, 부천위브트레지움2단지아파트)",NaN,NaN
999,서울특별시 서대문구 홍제동 460 인왕산현대아파트 109동 901호,"서울 서대문구 통일로34길 46 109동 901호 (홍제2동 460번지, 인왕산현대...",서울 서대문구 통일로34길 46,"109동 901호 (홍제2동 460번지, 인왕산현대아파트)",NaN,NaN
1000,부산광역시 기장군 정관면 모전리 휴먼시아2차아파트 (201~215동) 204 동105 동,"부산 기장군 정관읍 정관2로 24 204동 105호 (모전리 768번지, 휴먼시아2...",부산 기장군 정관읍 정관2로 24,"204동 105호 (모전리 768번지, 휴먼시아2차아파트)",NaN,NaN

In [7]:
address_data_[3]
for i in address_data_[3][1]:
    print(i, end=', ')
print('')    
print(len(address_data_[3][1]))

1, 0, 4, 동,  , 5, 0, 2, 호,  , (, 양, 벌, 리,  , 1, 1, 0, 4, 번, 지, ,,  , 양, 벌, 리, 세, 양, 청, 마, 루, 아, 파, 트, ),
35

In [8]:
address

array([['d.recipientaddr'],
       ['경기도 광주시 오포읍 양벌리 1104 양벌리 세양 청마루 아파트 104-502'],
       ['대전광역시 서구 도산로403번길 21 355호 ( 탄방동 )'],
       ...,
       ['경기도 부천시 약대동 209 부천위브트레지움2단지아파트 211동 1101호'],
       ['서울특별시 서대문구 홍제동 460 인왕산현대아파트 109동 901호'],
       ['부산광역시 기장군 정관면 모전리 휴먼시아2차아파트 (201~215동) 204 동105 동']],
      dtype='<U69')

In [9]:
sounds = list(set(''.join(address_data[3])) | set(''.join(address_data[2])) | set(''.join(address_data[0])) )
sounds.append('\n')
address_refined_size, vocab_size = len(address_data[1]), len(sounds)

In [10]:
print(address_refined_size)
print(vocab_size)

1001
589

In [11]:
print(sounds)

['구', '절', 'P', '출', '장', '째', '죽', '솔', '내', '필', 'D', '플', '아', '레', '찬', '영', '인', '잡', '립', '갈', '환', '워', '올', '괴', '8', '헐', '열', '헌', '박', '강', '촌', '쫄', '현', '린', '양', '존', '낙', '팔', '잔', '벌', '파', '맞', '곧', '접', '짓', '숙', '합', '타', '농', '선', '샛', '센', '팀', '칸', '터', '몽', '쁘', '쥬', '재', '~', '말', '랜', '횡', '공', '후', '기', '요', '알', '원', '경', '혁', '더', '검', '소', '굴', '깥', '샾', '랫', '날', '첸', '코', '본', '돼', '넓', '프', '쏠', '탁', '즈', '렬', '닛', '꿈', '햇', '옥', '션', '오', '심', '티', '제', '팰', '협', '씨', '탄', '다', '떡', '뜸', '곡', '초', '한', '보', '브', 'a', '맹', '독', '묘', 'L', '직', '년', '_', '교', '철', '율', '6', '우', '띠', '차', '퀘', '밍', '회', '킹', '월', '떼', '격', '벧', '가', '범', '령', '까', '불', '네', '늘', '긴', '석', 'y', '만', '엽', '밋', '락', '천', '봉', '웅', '슬', '자', '근', '윙', '록', '앙', '찰', '숯', '수', '곽', 'W', '진', '듀', '스', '극', '맨', '옆', '상', '백', '모', '족', '룸', '미', '른', 'r', '태', 'i', '번', '면', '산', '0', '뚝', '과', '점', '눈', '등', '거', '훈', '새', 'k', '샘', 'p', '첼', '님', '케', '숲', '담', '랄', '험', '트', '먼', 'ㅡ', '귀', '역', '럴', '텀', '패', 'A', '련', '빵', 't', '벨', '순', '육', 'E', '뷰', '텔', '온', '운', '톤', '대', '(', '폴', '루', '칠', 'Ⅳ', '7', '당', '발', '-', '일', '처', '라', '컬', '통', '삐', '또', '곤', '녹', '.', '중', '팅', '이', '저', '달', '노', '에', '투', '칼', 'v', '금', '켓', '웰', '딸', '러', '허', 'V', '입', '증', ',', '3', '탕', '서', '홈', '습', '뉴', '유', '&', '토', ' ', '책', '생', '효', 'l', '녕', '학', '닝', '병', '훼', '성', '지', '적', '로', '층', '고', '음', 'R', '승', '빙', '특', '그', '각', '은', '막', '켐', '두', '실', '느', '나', '니', '굿', '움', '참', '쿨', '홀', 'H', '랑', '여', '안', '권', '둥', '건', '암', '삼', 'm', '야', '뜨', '곶', '전', '분', '힐', '9', '료', '위', '준', '활', '골', '륜', '엔', '콜', '침', '동', '외', '덕', '펄', '하', '5', '팜', '형', '람', '빌', '임', '설', '호', '밭', '밸', '롯', '밤', 'd', '익', '판', '숭', '으', '방', '혜', '감', '추', '@', '좌', '앞', '왜', '쇠', '팬', '류', 'T', '주', '닉', '써', '애', '례', '궁', '촉', '캠', '리', '려', '섬', '창', '2', '측', '힘', '조', '물', 'M', '게', '해', '드', '손', '렛', '사', '옷', '속', '뜰', '능', '간', 'n', '울', '액', '비', '얄', '도', '틀', '뚜', '매', '난', '개', '용', '털', '갤', '픽', '릉', '괘', '읍', '예', '항', '디', '펜', 'K', '무', '신', '컵', '곰', '충', '청', '벤', '문', '틱', '너', '명', 'b', '럭', '흘', '페', '륭', '든', '민', '르', '홍', '마', '키', 'S', '벽', '체', '향', '베', '캐', '슈', '포', '첨', '첫', '바', '빛', '희', 's', '척', '함', '반', '악', '썬', '널', '쪽', 'Ⅱ', '언', '춘', '채', '식', '응', '/', '꽃', '편', 'G', '밀', '놀', '헤', '김', '단', '관', '풀', '계', '츠', '법', '테', '피', '변', '망', '풍', '샤', 'B', '집', '크', '규', '들', '샵', '래', '십', '앤', '블', '맥', '와', 'I', '윈', '링', '택', '연', '램', '시', '품', '버', '량', '딩', '귤', '답', '염', '롱', '턴', 'e', '길', '듬', '카', '견', '엘', '메', '젤', '쉘', '업', '란', '약', '황', '룡', '남', '논', '국', '술', '광', '정', '잠', '펠', '밥', '완', '4', '송', '흥', '뫼', '부', ')', 'c', '화', '탑', '군', '배', '솜', '최', '작', '흑', '별', '북', '쇄', '돌', '목', '엠', '누', '쌍', '글', '획', '클', '1', '행', '쉐', '평', '빗', ':', 'C', '젠', '세', '종', '왕', '치', '어', '림', '퍼', '휴', '커', '의', '데', '을', '푸', 'J', '름', '복', '\n']

In [12]:
char_to_ix = { ch:i for i,ch in enumerate(sorted(sounds)) }
ix_to_char = { i:ch for i,ch in enumerate(sorted(sounds)) }

In [13]:
print(ix_to_char)

{0: '\n', 1: ' ', 2: '&', 3: '(', 4: ')', 5: ',', 6: '-', 7: '.', 8: '/', 9: '0', 10: '1', 11: '2', 12: '3', 13: '4', 14: '5', 15: '6', 16: '7', 17: '8', 18: '9', 19: ':', 20: '@', 21: 'A', 22: 'B', 23: 'C', 24: 'D', 25: 'E', 26: 'G', 27: 'H', 28: 'I', 29: 'J', 30: 'K', 31: 'L', 32: 'M', 33: 'P', 34: 'R', 35: 'S', 36: 'T', 37: 'V', 38: 'W', 39: '_', 40: 'a', 41: 'b', 42: 'c', 43: 'd', 44: 'e', 45: 'i', 46: 'k', 47: 'l', 48: 'm', 49: 'n', 50: 'p', 51: 'r', 52: 's', 53: 't', 54: 'v', 55: 'y', 56: '~', 57: 'Ⅱ', 58: 'Ⅳ', 59: 'ㅡ', 60: '가', 61: '각', 62: '간', 63: '갈', 64: '감', 65: '강', 66: '개', 67: '갤', 68: '거', 69: '건', 70: '검', 71: '게', 72: '격', 73: '견', 74: '경', 75: '계', 76: '고', 77: '곡', 78: '곤', 79: '곧', 80: '골', 81: '곰', 82: '공', 83: '곶', 84: '과', 85: '곽', 86: '관', 87: '광', 88: '괘', 89: '괴', 90: '교', 91: '구', 92: '국', 93: '군', 94: '굴', 95: '굿', 96: '궁', 97: '권', 98: '귀', 99: '규', 100: '귤', 101: '그', 102: '극', 103: '근', 104: '글', 105: '금', 106: '기', 107: '긴', 108: '길', 109: '김', 110: '까', 111: '깥', 112: '꽃', 113: '꿈', 114: '나', 115: '낙', 116: '난', 117: '날', 118: '남', 119: '내', 120: '너', 121: '널', 122: '넓', 123: '네', 124: '년', 125: '녕', 126: '노', 127: '녹', 128: '논', 129: '놀', 130: '농', 131: '누', 132: '눈', 133: '뉴', 134: '느', 135: '늘', 136: '능', 137: '니', 138: '닉', 139: '님', 140: '닛', 141: '닝', 142: '다', 143: '단', 144: '달', 145: '담', 146: '답', 147: '당', 148: '대', 149: '더', 150: '덕', 151: '데', 152: '도', 153: '독', 154: '돌', 155: '동', 156: '돼', 157: '두', 158: '둥', 159: '듀', 160: '드', 161: '든', 162: '들', 163: '듬', 164: '등', 165: '디', 166: '딩', 167: '딸', 168: '떡', 169: '떼', 170: '또', 171: '뚜', 172: '뚝', 173: '뜨', 174: '뜰', 175: '뜸', 176: '띠', 177: '라', 178: '락', 179: '란', 180: '랄', 181: '람', 182: '랑', 183: '래', 184: '랜', 185: '램', 186: '랫', 187: '량', 188: '러', 189: '럭', 190: '럴', 191: '레', 192: '렛', 193: '려', 194: '련', 195: '렬', 196: '령', 197: '례', 198: '로', 199: '록', 200: '롯', 201: '롱', 202: '료', 203: '룡', 204: '루', 205: '룸', 206: '류', 207: '륜', 208: '륭', 209: '르', 210: '른', 211: '름', 212: '릉', 213: '리', 214: '린', 215: '림', 216: '립', 217: '링', 218: '마', 219: '막', 220: '만', 221: '말', 222: '망', 223: '맞', 224: '매', 225: '맥', 226: '맨', 227: '맹', 228: '먼', 229: '메', 230: '면', 231: '명', 232: '모', 233: '목', 234: '몽', 235: '뫼', 236: '묘', 237: '무', 238: '문', 239: '물', 240: '미', 241: '민', 242: '밀', 243: '밋', 244: '밍', 245: '바', 246: '박', 247: '반', 248: '발', 249: '밤', 250: '밥', 251: '방', 252: '밭', 253: '배', 254: '백', 255: '밸', 256: '버', 257: '번', 258: '벌', 259: '범', 260: '법', 261: '베', 262: '벤', 263: '벧', 264: '벨', 265: '벽', 266: '변', 267: '별', 268: '병', 269: '보', 270: '복', 271: '본', 272: '봉', 273: '부', 274: '북', 275: '분', 276: '불', 277: '뷰', 278: '브', 279: '블', 280: '비', 281: '빌', 282: '빗', 283: '빙', 284: '빛', 285: '빵', 286: '쁘', 287: '삐', 288: '사', 289: '산', 290: '삼', 291: '상', 292: '새', 293: '샘', 294: '샛', 295: '생', 296: '샤', 297: '샵', 298: '샾', 299: '서', 300: '석', 301: '선', 302: '설', 303: '섬', 304: '성', 305: '세', 306: '센', 307: '션', 308: '소', 309: '속', 310: '손', 311: '솔', 312: '솜', 313: '송', 314: '쇄', 315: '쇠', 316: '수', 317: '숙', 318: '순', 319: '술', 320: '숭', 321: '숯', 322: '숲', 323: '쉐', 324: '쉘', 325: '슈', 326: '스', 327: '슬', 328: '습', 329: '승', 330: '시', 331: '식', 332: '신', 333: '실', 334: '심', 335: '십', 336: '쌍', 337: '써', 338: '썬', 339: '쏠', 340: '씨', 341: '아', 342: '악', 343: '안', 344: '알', 345: '암', 346: '앙', 347: '앞', 348: '애', 349: '액', 350: '앤', 351: '야', 352: '약', 353: '얄', 354: '양', 355: '어', 356: '언', 357: '업', 358: '에', 359: '엔', 360: '엘', 361: '엠', 362: '여', 363: '역', 364: '연', 365: '열', 366: '염', 367: '엽', 368: '영', 369: '옆', 370: '예', 371: '오', 372: '옥', 373: '온', 374: '올', 375: '옷', 376: '와', 377: '완', 378: '왕', 379: '왜', 380: '외', 381: '요', 382: '용', 383: '우', 384: '운', 385: '울', 386: '움', 387: '웅', 388: '워', 389: '원', 390: '월', 391: '웰', 392: '위', 393: '윈', 394: '윙', 395: '유', 396: '육', 397: '율', 398: '으', 399: '은', 400: '을', 401: '음', 402: '읍', 403: '응', 404: '의', 405: '이', 406: '익', 407: '인', 408: '일', 409: '임', 410: '입', 411: '자', 412: '작', 413: '잔', 414: '잠', 415: '잡', 416: '장', 417: '재', 418: '저', 419: '적', 420: '전', 421: '절', 422: '점', 423: '접', 424: '정', 425: '제', 426: '젠', 427: '젤', 428: '조', 429: '족', 430: '존', 431: '종', 432: '좌', 433: '주', 434: '죽', 435: '준', 436: '중', 437: '쥬', 438: '즈', 439: '증', 440: '지', 441: '직', 442: '진', 443: '집', 444: '짓', 445: '째', 446: '쪽', 447: '쫄', 448: '차', 449: '찬', 450: '찰', 451: '참', 452: '창', 453: '채', 454: '책', 455: '처', 456: '척', 457: '천', 458: '철', 459: '첨', 460: '첫', 461: '청', 462: '체', 463: '첸', 464: '첼', 465: '초', 466: '촉', 467: '촌', 468: '최', 469: '추', 470: '춘', 471: '출', 472: '충', 473: '츠', 474: '측', 475: '층', 476: '치', 477: '칠', 478: '침', 479: '카', 480: '칸', 481: '칼', 482: '캐', 483: '캠', 484: '커', 485: '컬', 486: '컵', 487: '케', 488: '켐', 489: '켓', 490: '코', 491: '콜', 492: '쿨', 493: '퀘', 494: '크', 495: '클', 496: '키', 497: '킹', 498: '타', 499: '탁', 500: '탄', 501: '탑', 502: '탕', 503: '태', 504: '택', 505: '터', 506: '턴', 507: '털', 508: '텀', 509: '테', 510: '텔', 511: '토', 512: '톤', 513: '통', 514: '투', 515: '트', 516: '특', 517: '틀', 518: '티', 519: '틱', 520: '팀', 521: '팅', 522: '파', 523: '판', 524: '팔', 525: '팜', 526: '패', 527: '팬', 528: '팰', 529: '퍼', 530: '펄', 531: '페', 532: '펜', 533: '펠', 534: '편', 535: '평', 536: '포', 537: '폴', 538: '푸', 539: '풀', 540: '품', 541: '풍', 542: '프', 543: '플', 544: '피', 545: '픽', 546: '필', 547: '하', 548: '학', 549: '한', 550: '함', 551: '합', 552: '항', 553: '해', 554: '햇', 555: '행', 556: '향', 557: '허', 558: '헌', 559: '헐', 560: '험', 561: '헤', 562: '혁', 563: '현', 564: '협', 565: '형', 566: '혜', 567: '호', 568: '홀', 569: '홈', 570: '홍', 571: '화', 572: '환', 573: '활', 574: '황', 575: '회', 576: '획', 577: '횡', 578: '효', 579: '후', 580: '훈', 581: '훼', 582: '휴', 583: '흑', 584: '흘', 585: '흥', 586: '희', 587: '힐', 588: '힘'}

In [14]:
print(char_to_ix)

{'\n': 0, ' ': 1, '&': 2, '(': 3, ')': 4, ',': 5, '-': 6, '.': 7, '/': 8, '0': 9, '1': 10, '2': 11, '3': 12, '4': 13, '5': 14, '6': 15, '7': 16, '8': 17, '9': 18, ':': 19, '@': 20, 'A': 21, 'B': 22, 'C': 23, 'D': 24, 'E': 25, 'G': 26, 'H': 27, 'I': 28, 'J': 29, 'K': 30, 'L': 31, 'M': 32, 'P': 33, 'R': 34, 'S': 35, 'T': 36, 'V': 37, 'W': 38, '_': 39, 'a': 40, 'b': 41, 'c': 42, 'd': 43, 'e': 44, 'i': 45, 'k': 46, 'l': 47, 'm': 48, 'n': 49, 'p': 50, 'r': 51, 's': 52, 't': 53, 'v': 54, 'y': 55, '~': 56, 'Ⅱ': 57, 'Ⅳ': 58, 'ㅡ': 59, '가': 60, '각': 61, '간': 62, '갈': 63, '감': 64, '강': 65, '개': 66, '갤': 67, '거': 68, '건': 69, '검': 70, '게': 71, '격': 72, '견': 73, '경': 74, '계': 75, '고': 76, '곡': 77, '곤': 78, '곧': 79, '골': 80, '곰': 81, '공': 82, '곶': 83, '과': 84, '곽': 85, '관': 86, '광': 87, '괘': 88, '괴': 89, '교': 90, '구': 91, '국': 92, '군': 93, '굴': 94, '굿': 95, '궁': 96, '권': 97, '귀': 98, '규': 99, '귤': 100, '그': 101, '극': 102, '근': 103, '글': 104, '금': 105, '기': 106, '긴': 107, '길': 108, '김': 109, '까': 110, '깥': 111, '꽃': 112, '꿈': 113, '나': 114, '낙': 115, '난': 116, '날': 117, '남': 118, '내': 119, '너': 120, '널': 121, '넓': 122, '네': 123, '년': 124, '녕': 125, '노': 126, '녹': 127, '논': 128, '놀': 129, '농': 130, '누': 131, '눈': 132, '뉴': 133, '느': 134, '늘': 135, '능': 136, '니': 137, '닉': 138, '님': 139, '닛': 140, '닝': 141, '다': 142, '단': 143, '달': 144, '담': 145, '답': 146, '당': 147, '대': 148, '더': 149, '덕': 150, '데': 151, '도': 152, '독': 153, '돌': 154, '동': 155, '돼': 156, '두': 157, '둥': 158, '듀': 159, '드': 160, '든': 161, '들': 162, '듬': 163, '등': 164, '디': 165, '딩': 166, '딸': 167, '떡': 168, '떼': 169, '또': 170, '뚜': 171, '뚝': 172, '뜨': 173, '뜰': 174, '뜸': 175, '띠': 176, '라': 177, '락': 178, '란': 179, '랄': 180, '람': 181, '랑': 182, '래': 183, '랜': 184, '램': 185, '랫': 186, '량': 187, '러': 188, '럭': 189, '럴': 190, '레': 191, '렛': 192, '려': 193, '련': 194, '렬': 195, '령': 196, '례': 197, '로': 198, '록': 199, '롯': 200, '롱': 201, '료': 202, '룡': 203, '루': 204, '룸': 205, '류': 206, '륜': 207, '륭': 208, '르': 209, '른': 210, '름': 211, '릉': 212, '리': 213, '린': 214, '림': 215, '립': 216, '링': 217, '마': 218, '막': 219, '만': 220, '말': 221, '망': 222, '맞': 223, '매': 224, '맥': 225, '맨': 226, '맹': 227, '먼': 228, '메': 229, '면': 230, '명': 231, '모': 232, '목': 233, '몽': 234, '뫼': 235, '묘': 236, '무': 237, '문': 238, '물': 239, '미': 240, '민': 241, '밀': 242, '밋': 243, '밍': 244, '바': 245, '박': 246, '반': 247, '발': 248, '밤': 249, '밥': 250, '방': 251, '밭': 252, '배': 253, '백': 254, '밸': 255, '버': 256, '번': 257, '벌': 258, '범': 259, '법': 260, '베': 261, '벤': 262, '벧': 263, '벨': 264, '벽': 265, '변': 266, '별': 267, '병': 268, '보': 269, '복': 270, '본': 271, '봉': 272, '부': 273, '북': 274, '분': 275, '불': 276, '뷰': 277, '브': 278, '블': 279, '비': 280, '빌': 281, '빗': 282, '빙': 283, '빛': 284, '빵': 285, '쁘': 286, '삐': 287, '사': 288, '산': 289, '삼': 290, '상': 291, '새': 292, '샘': 293, '샛': 294, '생': 295, '샤': 296, '샵': 297, '샾': 298, '서': 299, '석': 300, '선': 301, '설': 302, '섬': 303, '성': 304, '세': 305, '센': 306, '션': 307, '소': 308, '속': 309, '손': 310, '솔': 311, '솜': 312, '송': 313, '쇄': 314, '쇠': 315, '수': 316, '숙': 317, '순': 318, '술': 319, '숭': 320, '숯': 321, '숲': 322, '쉐': 323, '쉘': 324, '슈': 325, '스': 326, '슬': 327, '습': 328, '승': 329, '시': 330, '식': 331, '신': 332, '실': 333, '심': 334, '십': 335, '쌍': 336, '써': 337, '썬': 338, '쏠': 339, '씨': 340, '아': 341, '악': 342, '안': 343, '알': 344, '암': 345, '앙': 346, '앞': 347, '애': 348, '액': 349, '앤': 350, '야': 351, '약': 352, '얄': 353, '양': 354, '어': 355, '언': 356, '업': 357, '에': 358, '엔': 359, '엘': 360, '엠': 361, '여': 362, '역': 363, '연': 364, '열': 365, '염': 366, '엽': 367, '영': 368, '옆': 369, '예': 370, '오': 371, '옥': 372, '온': 373, '올': 374, '옷': 375, '와': 376, '완': 377, '왕': 378, '왜': 379, '외': 380, '요': 381, '용': 382, '우': 383, '운': 384, '울': 385, '움': 386, '웅': 387, '워': 388, '원': 389, '월': 390, '웰': 391, '위': 392, '윈': 393, '윙': 394, '유': 395, '육': 396, '율': 397, '으': 398, '은': 399, '을': 400, '음': 401, '읍': 402, '응': 403, '의': 404, '이': 405, '익': 406, '인': 407, '일': 408, '임': 409, '입': 410, '자': 411, '작': 412, '잔': 413, '잠': 414, '잡': 415, '장': 416, '재': 417, '저': 418, '적': 419, '전': 420, '절': 421, '점': 422, '접': 423, '정': 424, '제': 425, '젠': 426, '젤': 427, '조': 428, '족': 429, '존': 430, '종': 431, '좌': 432, '주': 433, '죽': 434, '준': 435, '중': 436, '쥬': 437, '즈': 438, '증': 439, '지': 440, '직': 441, '진': 442, '집': 443, '짓': 444, '째': 445, '쪽': 446, '쫄': 447, '차': 448, '찬': 449, '찰': 450, '참': 451, '창': 452, '채': 453, '책': 454, '처': 455, '척': 456, '천': 457, '철': 458, '첨': 459, '첫': 460, '청': 461, '체': 462, '첸': 463, '첼': 464, '초': 465, '촉': 466, '촌': 467, '최': 468, '추': 469, '춘': 470, '출': 471, '충': 472, '츠': 473, '측': 474, '층': 475, '치': 476, '칠': 477, '침': 478, '카': 479, '칸': 480, '칼': 481, '캐': 482, '캠': 483, '커': 484, '컬': 485, '컵': 486, '케': 487, '켐': 488, '켓': 489, '코': 490, '콜': 491, '쿨': 492, '퀘': 493, '크': 494, '클': 495, '키': 496, '킹': 497, '타': 498, '탁': 499, '탄': 500, '탑': 501, '탕': 502, '태': 503, '택': 504, '터': 505, '턴': 506, '털': 507, '텀': 508, '테': 509, '텔': 510, '토': 511, '톤': 512, '통': 513, '투': 514, '트': 515, '특': 516, '틀': 517, '티': 518, '틱': 519, '팀': 520, '팅': 521, '파': 522, '판': 523, '팔': 524, '팜': 525, '패': 526, '팬': 527, '팰': 528, '퍼': 529, '펄': 530, '페': 531, '펜': 532, '펠': 533, '편': 534, '평': 535, '포': 536, '폴': 537, '푸': 538, '풀': 539, '품': 540, '풍': 541, '프': 542, '플': 543, '피': 544, '픽': 545, '필': 546, '하': 547, '학': 548, '한': 549, '함': 550, '합': 551, '항': 552, '해': 553, '햇': 554, '행': 555, '향': 556, '허': 557, '헌': 558, '헐': 559, '험': 560, '헤': 561, '혁': 562, '현': 563, '협': 564, '형': 565, '혜': 566, '호': 567, '홀': 568, '홈': 569, '홍': 570, '화': 571, '환': 572, '활': 573, '황': 574, '회': 575, '획': 576, '횡': 577, '효': 578, '후': 579, '훈': 580, '훼': 581, '휴': 582, '흑': 583, '흘': 584, '흥': 585, '희': 586, '힐': 587, '힘': 588}

In [15]:
def clip(gradients, maxValue):
    '''
    Clips the gradients' values between minimum and maximum.
    
    Arguments:
    gradients -- a dictionary containing the gradients "dWaa", "dWax", "dWya", "db", "dby"
    maxValue -- everything above this number is set to this number, and everything less than -maxValue is set to -maxValue
    
    Returns: 
    gradients -- a dictionary with the clipped gradients.
    '''
    
    dWaa, dWax, dWya, db, dby = gradients['dWaa'], gradients['dWax'], gradients['dWya'], gradients['db'], gradients['dby']
   
    # clip to mitigate exploding gradients, loop over [dWax, dWaa, dWya, db, dby]. (≈2 lines)
    
    for gradient in [dWax, dWaa, dWya, db, dby]:
        np.clip(gradient, -maxValue, maxValue, out=gradient)
    
    gradients = {"dWaa": dWaa, "dWax": dWax, "dWya": dWya, "db": db, "dby": dby}
    
    return gradients

In [16]:
np.random.seed(3)
dWax = np.random.randn(5,3)*10
dWaa = np.random.randn(5,5)*10
dWya = np.random.randn(2,5)*10
db = np.random.randn(5,1)*10
dby = np.random.randn(2,1)*10
gradients = {"dWax": dWax, "dWaa": dWaa, "dWya": dWya, "db": db, "dby": dby}
gradients = clip(gradients, 10)
print("gradients[\"dWaa\"][1][2] =", gradients["dWaa"][1][2])
print("gradients[\"dWax\"][3][1] =", gradients["dWax"][3][1])
print("gradients[\"dWya\"][1][2] =", gradients["dWya"][1][2])
print("gradients[\"db\"][4] =", gradients["db"][4])
print("gradients[\"dby\"][1] =", gradients["dby"][1])

gradients["dWaa"][1][2] = 10.0
gradients["dWax"][3][1] = -10.0
gradients["dWya"][1][2] = 0.2971381536101662
gradients["db"][4] = [10.]
gradients["dby"][1] = [8.45833407]

In [17]:
def softmax(x):
    """Compute softmax values for each sets of scores in x."""
    e_x = np.exp(x - np.max(x))
    return e_x / e_x.sum()

In [18]:
# GRADED FUNCTION: sample

def sample(parameters, char_to_ix, seed):
    """
    Sample a sequence of characters according to a sequence of probability distributions output of the RNN

    Arguments:
    parameters -- python dictionary containing the parameters Waa, Wax, Wya, by, and b. 
    char_to_ix -- python dictionary mapping each character to an index.
    seed -- used for grading purposes. Do not worry about it.

    Returns:
    indices -- a list of length n containing the indices of the sampled characters.
    """
    
    # Retrieve parameters and relevant shapes from "parameters" dictionary
    Waa, Wax, Wya, by, b = parameters['Waa'], parameters['Wax'], parameters['Wya'], parameters['by'], parameters['b']
    vocab_size = by.shape[0]
    n_a = Waa.shape[1]
    
    # Step 1: Create the one-hot vector x for the first character (initializing the sequence generation). (≈1 line)
    x = np.zeros((vocab_size, 1))
    # Step 1': Initialize a_prev as zeros (≈1 line)
    a_prev = np.zeros((n_a, 1))
    
    # Create an empty list of indices, this is the list which will contain the list of indices of the characters to generate (≈1 line)
    indices = []
    
    # Idx is a flag to detect a newline character, we initialize it to -1
    idx = -1 
    
    # Loop over time-steps t. At each time-step, sample a character from a probability distribution and append 
    # its index to "indices". We'll stop if we reach 50 characters (which should be very unlikely with a well 
    # trained model), which helps debugging and prevents entering an infinite loop. 
    counter = 0
    newline_character = char_to_ix['\n']
    
    while (idx != newline_character and counter != 50):
        
        # Step 2: Forward propagate x using the equations (1), (2) and (3)
        a = np.tanh(np.dot(Wax, x) + np.dot(Waa, a_prev) + b)
        z = np.dot(Wya, a) + by
        y = softmax(z)
        
        # for grading purposes
        np.random.seed(counter+seed) 
        
        # Step 3: Sample the index of a character within the vocabulary from the probability distribution y
        idx = np.random.choice(list(range(vocab_size)), p=y.ravel())
        # Append the index to "indices"
        indices.append(idx)
        
        # Step 4: Overwrite the input character as the one corresponding to the sampled index.
        x = np.zeros((vocab_size, 1))
        x[idx] = 1
        
        # Update "a_prev" to be "a"
        a_prev = a
        
        # for grading purposes
        seed += 1
        counter +=1

    if (counter == 50):
        indices.append(char_to_ix['\n'])
    
    return indices

In [19]:
np.random.seed(2)
_, n_a = 20, 100
Wax, Waa, Wya = np.random.randn(n_a, vocab_size), np.random.randn(n_a, n_a), np.random.randn(vocab_size, n_a)
b, by = np.random.randn(n_a, 1), np.random.randn(vocab_size, 1)
parameters = {"Wax": Wax, "Waa": Waa, "Wya": Wya, "b": b, "by": by}


indices = sample(parameters, char_to_ix, 0)
print("Sampling:")
print("list of sampled indices:", indices)
print("list of sampled characters:", [ix_to_char[i] for i in indices])

Sampling:
list of sampled indices: [306, 112, 475, 555, 303, 182, 272, 355, 191, 198, 476, 128, 478, 279, 267, 272, 513, 84, 272, 439, 564, 240, 361, 294, 315, 296, 218, 191, 514, 152, 363, 528, 461, 147, 34, 501, 159, 192, 258, 461, 476, 522, 240, 547, 130, 296, 468, 365, 490, 42, 0]
list of sampled characters: ['센', '꽃', '층', '행', '섬', '랑', '봉', '어', '레', '로', '치', '논', '침', '블', '별', '봉', '통', '과', '봉', '증', '협', '미', '엠', '샛', '쇠', '샤', '마', '레', '투', '도', '역', '팰', '청', '당', 'R', '탑', '듀', '렛', '벌', '청', '치', '파', '미', '하', '농', '샤', '최', '열', '코', 'c', '\n']

In [20]:
from __future__ import print_function
from keras.callbacks import LambdaCallback
from keras.models import Model, load_model, Sequential
from keras.layers import Dense, Activation, Dropout, Input, Masking
from keras.layers import LSTM
from keras.utils.data_utils import get_file
from keras.preprocessing.sequence import pad_sequences

import sys
import io

Using TensorFlow backend.

In [22]:
print_callback = LambdaCallback(on_epoch_end=on_epoch_end)

model.fit(x, y, batch_size=128, epochs=1, callbacks=[print_callback])

NameError: name 'on_epoch_end' is not defined

In [22]:
train_data = pandas.read_csv('../data/11-10-00to06.csv', sep = '\t', header = None)
train_data_ = train_data
address_t = np.array([x.split(';') for x in address_data_[0]])

In [23]:
train_data

,0,1,2,3,4,5
0,"경기도 부천시 상일로 71 1818동 1505호 ( 상동, 반달마을 건영,동아,선경...","경기 부천시 상일로 71 1818동 1505호 (상1동 397번지, 반달마을건영동아...",경기 부천시 상일로 71,"1818동 1505호 (상1동 397번지, 반달마을건영동아선경아파트)",1818,1505
1,서울특별시 동대문구 한천로63길 10 이문e편한세상아파트 114동 1602호 ( 이...,"서울 동대문구 한천로63길 10 114동 1602호 (이문2동 225번지, 이문e편...",서울 동대문구 한천로63길 10,"114동 1602호 (이문2동 225번지, 이문e편한세상아파트)",114,1602
2,경기도 시흥시 정왕동 2575 시흥배곧신도시 이지더원2차 에듀그린 207동 502호,"경기 시흥시 서울대학로 100 207동 502호 (정왕동 2575번지, 시흥배곧신도...",경기 시흥시 서울대학로 100,"207동 502호 (정왕동 2575번지, 시흥배곧신도시이지더원2차에듀그린)",207,502
3,경상북도 구미시 옥계동 906 구미옥계우미린 101동2401호,"경북 구미시 해마루공원로 111 101동 2401호 (옥계동 906번지, 구미옥계우미린)",경북 구미시 해마루공원로 111,"101동 2401호 (옥계동 906번지, 구미옥계우미린)",101,2401
4,경기도 남양주시 진접읍 금곡리 1098 휴먼시아17단지아파트 1712동 206호,"경기 남양주시 진접읍 해밀예당3로 37 1712동 206호 (금곡리 1098번지, ...",경기 남양주시 진접읍 해밀예당3로 37,"1712동 206호 (금곡리 1098번지, 휴먼시아17단지아파트)",1712,206
5,울산광역시 북구 효문동 50 효문코오롱하늘채 104/2003,"울산 북구 율동2길 8 104동 2003호 (효문동 50번지, 효문코오롱하늘채)",울산 북구 율동2길 8,"104동 2003호 (효문동 50번지, 효문코오롱하늘채)",104,2003
6,경기도 용인시 수지구 죽전동 새터마을 힐스테이트 702-1701,경기 용인시 수지구 현암로125번길 11 702동 1701호 (죽전1동 1165번지...,경기 용인시 수지구 현암로125번길 11,"702동 1701호 (죽전1동 1165번지, 새터마을힐스테이트)",702,1701
7,"경기도 수원시 장안구 장안로 232 동신아파트104동 904호 ( 정자동,동신아파트 )","경기 수원시 장안구 장안로 232 104동 904호 (정자1동 401번지, 동신아파트)",경기 수원시 장안구 장안로 232,"104동 904호 (정자1동 401번지, 동신아파트)",104,904
8,서울 중랑구 면목2동 면목한신아파트 8동 1106호,"서울 중랑구 중랑천로 20 8동 1106호 (면목2동 193-1번지, 면목한신아파트)",서울 중랑구 중랑천로 20,"8동 1106호 (면목2동 193-1번지, 면목한신아파트)",8,1106
9,인천광역시 남동구 논현동 604-1 냇마을신영지웰아파트 908동 504호,"인천 남동구 소래역로 93 908동 504호 (논현동 604-1번지, 냇마을신영지웰...",인천 남동구 소래역로 93,"908동 504호 (논현동 604-1번지, 냇마을신영지웰아파트)",908,504
10,서울특별시 강동구 암사동 413 프라이어팰리스 115-402,"서울 강동구 고덕로 130 115동 402호 (암사1동 413번지, 프라이어팰리스)",서울 강동구 고덕로 130,"115동 402호 (암사1동 413번지, 프라이어팰리스)",115,402
11,서울특별시 도봉구 방학3동 신동아1단지아파트 (20~31동) 20동1103호,"서울 도봉구 방학로 193 20동 1103호 (방학3동 272-2번지, 신동아1단지...",서울 도봉구 방학로 193,"20동 1103호 (방학3동 272-2번지, 신동아1단지아파트)",20,1103
12,충청북도 청주시 청원구 오창읍 주성리 569번지 부영아파트6단지 603-504,"충북 청주시 청원구 오창읍 2산단로 125 603동 504호 (주성리 569번지, ...",충북 청주시 청원구 오창읍 2산단로 125,"603동 504호 (주성리 569번지, 부영아파트6단지)",603,504
13,울산광역시 북구 호계매곡1로 32 드림in시티 에일린의 뜰 2차 206동 2902호...,울산 북구 호계매곡1로 32 드림in시티 에일린의 뜰 2차 206동 2902호 (매...,울산 북구 호계매곡1로 32,"드림in시티 에일린의 뜰 2차 206동 2902호 (매곡동 97번지, 드림인시티 에...",\N,\N
14,울산광역시 북구 산하동 푸르지오2차 106동1004호,"울산 북구 강동산하2로 43 106동 1004호 (산하동 442번지, 푸르지오2차)",울산 북구 강동산하2로 43,"106동 1004호 (산하동 442번지, 푸르지오2차)",106,1004
15,"서울특별시 노원구 공릉로 351 하계동 한신아파트 2동 1519호 ( 하계동, 한신...","서울 노원구 공릉로 351 2동 1519호 (하계1동 284번지, 하계동한신아파트)",서울 노원구 공릉로 351,"2동 1519호 (하계1동 284번지, 하계동한신아파트)",2,1519
16,"경기도 수원시 영통구 중부대로271번길 27-9 104동 1306호 ( 원천동, 주...",경기 수원시 영통구 중부대로271번길 27-9 104동 1306호 (원천동 35번지...,경기 수원시 영통구 중부대로271번길 27-9,"104동 1306호 (원천동 35번지, 주공아파트)",104,1306
17,서울특별시 성동구 하왕십리동 339-67 텐즈힐1아파트 113동 604호,"서울 성동구 무학로 33 113동 604호 (하왕십리동 1066번지, 텐즈힐1아파트)",서울 성동구 무학로 33,"113동 604호 (하왕십리동 1066번지, 텐즈힐1아파트)",113,604
18,인천광역시 부평구 부평동 947 래미안부평 108동1504호,"인천 부평구 길주남로10번길 21 108동 1504호 (부평1동 947번지, 래미안부평)",인천 부평구 길주남로10번길 21,"108동 1504호 (부평1동 947번지, 래미안부평)",108,1504
19,서울특별시 강남구 개포동 대치아파트 (101~108동) 103동 1313호,"서울 강남구 개포로109길 5 103동 1313호 (개포동 12번지, 대치아파트)",서울 강남구 개포로109길 5,"103동 1313호 (개포동 12번지, 대치아파트)",103,1313
20,"서울특별시 강서구 허준로 175 601동 101호 ( 가양동, 가양6단지아파트 )","서울 강서구 허준로 175 601동 101호 (가양3동 1485번지, 가양6단지아파트)",서울 강서구 허준로 175,"601동 101호 (가양3동 1485번지, 가양6단지아파트)",601,101
21,"서울특별시 성북구 길음로 118 405-704 길음뉴타운,길음동","서울 성북구 길음로 118 405-704 길음뉴타운,길음동 (길음1동 1281번지)",서울 성북구 길음로 118,"405-704 길음뉴타운,길음동 (길음1동 1281번지)",405,704
22,경상남도 창원시 성산구 상남동 45-1 성원아파트 202동1407호,"경남 창원시 성산구 원이대로 774 202동 1407호 (상남동 45-1번지, 성원...",경남 창원시 성산구 원이대로 774,"202동 1407호 (상남동 45-1번지, 성원아파트)",202,1407
23,경기도 안산시 상록구 사1동 푸른마을주공5단지아파트 (501~521동) 507-801,"경기 안산시 상록구 광덕4로 460 507동 801호 (사1동 1536번지, 푸른마...",경기 안산시 상록구 광덕4로 460,"507동 801호 (사1동 1536번지, 푸른마을주공5단지아파트)",507,801
24,서울특별시 동대문구 장안동 336 장안현대홈타운 113동 1503호,"서울 동대문구 장안벚꽃로 107 113동 1503호 (장안1동 336번지, 장안현대...",서울 동대문구 장안벚꽃로 107,"113동 1503호 (장안1동 336번지, 장안현대홈타운)",113,1503
25,부산광역시 남구 용호동 944 오륙도 에스케이뷰 아파트 105동 3004호,"부산 남구 오륙도로 85 105동 3004호 (용호2동 944번지, 오륙도에스케이뷰...",부산 남구 오륙도로 85,"105동 3004호 (용호2동 944번지, 오륙도에스케이뷰아파트)",105,3004
26,대구 달서구 유천동 103번지 AK그랑폴리스 110동 2203호,"대구 달서구 월배로11길 33 110동 2203호 (유천동 597번지, AK그랑폴리스)",대구 달서구 월배로11길 33,"110동 2203호 (유천동 597번지, AK그랑폴리스)",110,2203
27,부산광역시 남구 용호동 176-30 엘지메트로시티 121동503호,"부산 남구 분포로 111 121동 503호 (용호1동 176-30번지, 엘지메트로시티)",부산 남구 분포로 111,"121동 503호 (용호1동 176-30번지, 엘지메트로시티)",121,503
28,"경기도 안산시 상록구 화랑로 495 예술인아파트 2동1210호 ( 성포동, 예술인아...","경기 안산시 상록구 화랑로 495 2동 1210호 (성포동 583번지, 예술인아파트)",경기 안산시 상록구 화랑로 495,"2동 1210호 (성포동 583번지, 예술인아파트)",2,1210
29,대구광역시 북구 사수동 789 브라운스톤 강북 307동1704호,"대구 북구 내곡로 89 307동 1704호 (사수동 789번지, 브라운스톤강북)",대구 북구 내곡로 89,"307동 1704호 (사수동 789번지, 브라운스톤강북)",307,1704
...,...,...,...,...,...,...
25508,대구광역시 달서구 유천동 605 대구월배아이파크 113동 1105호,"대구 달서구 조암남로 182 113동 1105호 (유천동 605번지, 대구월배아이파크)",대구 달서구 조암남로 182,"113동 1105호 (유천동 605번지, 대구월배아이파크)",113,1105
25509,인천광역시 연수구 송도동 192-1 송도더샵그린스퀘어 103동 2004호,"인천 연수구 송도문화로28번길 81 103동 2004호 (송도3동 192-1번지, ...",인천 연수구 송도문화로28번길 81,"103동 2004호 (송도3동 192-1번지, 송도더샵그린스퀘어)",103,2004
25510,경기도 남양주시 별내동 1047 신안인스빌아파트 4105동603호,"경기 남양주시 순화궁로 18 4105동 603호 (별내동 1047번지, 신안인스빌아파트)",경기 남양주시 순화궁로 18,"4105동 603호 (별내동 1047번지, 신안인스빌아파트)",4105,603
25511,인천광역시 남동구 논현동 603-1 휴먼시아동산마을8단지아파트 801동 1901호,"인천 남동구 소래역로 119 801동 1901호 (논현동 603-1번지, 휴먼시아동...",인천 남동구 소래역로 119,"801동 1901호 (논현동 603-1번지, 휴먼시아동산마을8단지아파트)",801,1901
25512,"서울특별시 강남구 삼성로 212 은마아파트, 5-909 ( 대치동, 은마아파트 )","서울 강남구 삼성로 212 5동 909호 (대치2동 316번지, 은마아파트)",서울 강남구 삼성로 212,"5동 909호 (대치2동 316번지, 은마아파트)",5,909
25513,"경기도 광명시 목감로 58 해모로이연아파트 110동 304호 ( 광명동, 광명해모로...","경기 광명시 목감로 58 110동 304호 (광명6동 785번지, 해모로이연아파트)",경기 광명시 목감로 58,"110동 304호 (광명6동 785번지, 해모로이연아파트)",110,304
25514,"서울특별시 노원구 중계동 505 경남,롯데,상아아파트 상아아파트 17동 803호",서울 노원구 섬밭로 265 17동 803호 (중계2.3동 505번지),서울 노원구 섬밭로 265,17동 803호 (중계2.3동 505번지),17,803
25515,경기도 파주시 금촌동 1003 쇠재마을아파트 506동 904호,"경기 파주시 쇠재로 133 506동 904호 (금촌2동 1003번지, 쇠재마을아파트)",경기 파주시 쇠재로 133,"506동 904호 (금촌2동 1003번지, 쇠재마을아파트)",506,904
25516,"인천광역시 남동구 호구포로 924 108-2403 ( 만수동, 햇빛마을벽산아파트 )","인천 남동구 호구포로 924 108동 2403호 (만수3동 1114번지, 햇빛마을벽...",인천 남동구 호구포로 924,"108동 2403호 (만수3동 1114번지, 햇빛마을벽산아파트)",108,2403
25517,서울특별시 관악구 신림동 1730 신림푸르지오아파트 105-1702,"서울 관악구 남부순환로 1430 105동 1702호 (미성동 1730번지, 신림푸르...",서울 관악구 남부순환로 1430,"105동 1702호 (미성동 1730번지, 신림푸르지오아파트)",105,1702
25518,서울특별시 성동구 행당동 행당대림아파트 112-1104,"서울 성동구 행당로 79 112동 1104호 (행당2동 347번지, 행당대림아파트)",서울 성동구 행당로 79,"112동 1104호 (행당2동 347번지, 행당대림아파트)",112,1104
25519,경기도 남양주시 진접읍 금곡리 1108 금강펜테리움아파트 1906동1004호,"경기 남양주시 진접읍 해밀예당3로 68 1906동 1004호 (금곡리 1108번지,...",경기 남양주시 진접읍 해밀예당3로 68,"1906동 1004호 (금곡리 1108번지, 금강펜테리움아파트)",1906,1004
25520,경기도 용인시 기흥구 영덕동 976 흥덕마을5단지 호반베르디움 508동 1703호,"경기 용인시 기흥구 흥덕1로79번길 37 508동 1703호 (영덕동 976번지, ...",경기 용인시 기흥구 흥덕1로79번길 37,"508동 1703호 (영덕동 976번지, 흥덕마을5단지호반베르디움)",508,1703
25521,경기도 수원시 영통구 원천동 호반베르디움 1009동 1003호,"경기 수원시 영통구 광교호수공원로 45 1009동 1003호 (원천동 606번지, ...",경기 수원시 영통구 광교호수공원로 45,"1009동 1003호 (원천동 606번지, 호반베르디움)",1009,1003
25522,충청북도 청원군 오창읍 각리 중앙하이츠아파트 (201~214동) 202-104호,"충북 청주시 청원구 오창읍 오창중앙로 32 202동 104호 (각리 637-6번지,...",충북 청주시 청원구 오창읍 오창중앙로 32,"202동 104호 (각리 637-6번지, 중앙하이츠아파트)",202,104
25523,서울특별시 도봉구 방학동 271-1 신동아1단지아파트 8동 203호,"서울 도봉구 방학로 193 8동 203호 (방학3동 272번지, 신동아1단지아파트)",서울 도봉구 방학로 193,"8동 203호 (방학3동 272번지, 신동아1단지아파트)",8,203
25524,경기도 용인시 수지구 상현동 866 상현마을성원상떼빌아파트 232동 1701호,"경기 용인시 수지구 상현로 30-10 232동 1701호 (상현1동 866번지, 상...",경기 용인시 수지구 상현로 30-10,"232동 1701호 (상현1동 866번지, 상현마을성원상떼빌아파트)",232,1701
25525,"경기도 성남시 분당구 서현동 308 효자촌대우,럭키,화성아파트 623동 1505호","경기 성남시 분당구 불정로 362 623동 1505호 (서현동 308번지, 효자촌대...",경기 성남시 분당구 불정로 362,"623동 1505호 (서현동 308번지, 효자촌대우럭키화성아파트)",623,1505
25526,서울특별시 서초구 잠원동 73 신반포2지구아파트 103동 710호,"서울 서초구 신반포로23길 41 103동 710호 (잠원동 73번지, 신반포2지구아파트)",서울 서초구 신반포로23길 41,"103동 710호 (잠원동 73번지, 신반포2지구아파트)",103,710
25527,인천광역시 남동구 논현동 603-1 휴먼시아동산마을8단지아파트 801동 1901호,"인천 남동구 소래역로 119 801동 1901호 (논현동 603-1번지, 휴먼시아동...",인천 남동구 소래역로 119,"801동 1901호 (논현동 603-1번지, 휴먼시아동산마을8단지아파트)",801,1901
25528,"경기도 고양시 일산동구 위시티4로 80 111동1603호 ( 식사동,위시티일산자이1...","경기 고양시 일산동구 위시티4로 80 111동 1603호 (식사동 1487번지, 위...",경기 고양시 일산동구 위시티4로 80,"111동 1603호 (식사동 1487번지, 위시티일산자이1단지아파트)",111,1603
25529,경기도 수원시 영통구 매탄동 1352 매탄 위브 하늘채 102동 2003호,"경기 수원시 영통구 효원로 363 102동 2003호 (매탄3동 1352번지, 매탄...",경기 수원시 영통구 효원로 363,"102동 2003호 (매탄3동 1352번지, 매탄위브하늘채)",102,2003
25530,서울특별시 강서구 가양동 1485 가양6단지아파트 615동 402호,"서울 강서구 허준로 175 615동 402호 (가양3동 1485번지, 가양6단지아파트)",서울 강서구 허준로 175,"615동 402호 (가양3동 1485번지, 가양6단지아파트)",615,402
25531,"경기도 성남시 수정구 위례광장로 311 35단지 3507동1408호 ( 창곡동, 위...","경기 성남시 수정구 위례광장로 311 3507동 1408호 (창곡동 510번지, 위...",경기 성남시 수정구 위례광장로 311,"3507동 1408호 (창곡동 510번지, 위례35단지)",3507,1408
25532,경기도 군포시 산본2동 래미안하이어스아파트 (101~129동) 125-1602,"경기 군포시 금산로 91 125동 1602호 (산본2동 1241번지, 래미안하이어스...",경기 군포시 금산로 91,"125동 1602호 (산본2동 1241번지, 래미안하이어스아파트)",125,1602
25533,"서울특별시 강동구 고덕로 210 601동 1405호 ( 명일동, 삼익그린맨션 )","서울 강동구 고덕로 210 601동 1405호 (명일1동 15번지, 삼익그린맨션)",서울 강동구 고덕로 210,"601동 1405호 (명일1동 15번지, 삼익그린맨션)",601,1405
25534,경기도 성남시 분당구 이매동 124 이매촌한신아파트 212동2103호,"경기 성남시 분당구 서현로 181 212동 2103호 (이매동 124번지, 이매촌한...",경기 성남시 분당구 서현로 181,"212동 2103호 (이매동 124번지, 이매촌한신아파트)",212,2103
25535,"부산광역시 해운대구 센텀중앙로 145 111동 3705호 ( 재송동, 더샵센텀파크1...","부산 해운대구 센텀중앙로 145 111동 3705호 (재송1동 1200번지, 더샵센...",부산 해운대구 센텀중앙로 145,"111동 3705호 (재송1동 1200번지, 더샵센텀파크1차아파트)",111,3705
25536,경기도 하남시 선동 455 미사강변리버뷰자이 102동 1801호,"경기 하남시 미사강변한강로 10 102동 1801호 (선동 455번지, 미사강변리버...",경기 하남시 미사강변한강로 10,"102동 1801호 (선동 455번지, 미사강변리버뷰자이)",102,1801
25537,서울특별시 중랑구 신내동 우디안아파트204 동1103호,"서울 중랑구 신내역로 165 204동 1103호 (신내1동 817번지, 우디안아파트)",서울 중랑구 신내역로 165,"204동 1103호 (신내1동 817번지, 우디안아파트)",204,1103